import { StyleSheet } from 'react-native';
import { Colors, Spacing, Radius, Typography } from '@/constants/theme';

export const estilos = StyleSheet.create({
  segura: { flex: 1, backgroundColor: Colors.bg },
  scroll: { flex: 1 },
  conteudo: { paddingBottom: Spacing.xxl },

  containerBusca: {
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.sm,
    gap: Spacing.sm,
  },
  linhaBusca: {
    flexDirection: 'row',
    gap: Spacing.sm,
    alignItems: 'center',
  },
  inputBusca: {
    flex: 1,
    backgroundColor: Colors.bgCard,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    fontFamily: Typography.body,
    color: Colors.textPrimary,
    fontSize: 15,
  },
  botaoBusca: {
    backgroundColor: Colors.rust,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    justifyContent: 'center',
  },
  textoBotaoBusca: {
    fontFamily: Typography.display,
    color: Colors.textPrimary,
    fontSize: 11,
    letterSpacing: 1,
  },
  listaSugestoes: {
    backgroundColor: Colors.bgCard,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    overflow: 'hidden',
  },
  itemSugestao: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  nomeSugestao: {
    fontFamily: Typography.bodyMedium,
    color: Colors.textPrimary,
    fontSize: 14,
  },
  subSugestao: {
    fontFamily: Typography.body,
    color: Colors.textSecondary,
    fontSize: 11,
    marginTop: 1,
  },

  cardHero: {
    marginHorizontal: Spacing.md,
    marginBottom: Spacing.sm,
    borderRadius: Radius.lg,
    overflow: 'hidden',
  },
  bgHero: { width: '100%' },
  bgHeroImagem: { opacity: 0.25 },
  overlayHero: {
    backgroundColor: 'rgba(32, 39, 68, 0.7)',
    padding: Spacing.lg,
  },
  cidadeTexto: {
    fontFamily: Typography.display,
    color: Colors.textPrimary,
    fontSize: 22,
    letterSpacing: 2,
  },
  paisTexto: {
    fontFamily: Typography.body,
    color: Colors.textSecondary,
    fontSize: 13,
    marginBottom: Spacing.md,
  },
  linhaHeroTopo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  emojiClimaGrande: { fontSize: 56, lineHeight: 64 },
  blocoTempHero: { alignItems: 'flex-end' },
  tempHero: {
    fontFamily: Typography.display,
    color: Colors.amber,
    fontSize: 56,
    lineHeight: 60,
  },
  descClimaHero: {
    fontFamily: Typography.body,
    color: Colors.textSecondary,
    fontSize: 13,
    textAlign: 'right',
    marginTop: 2,
  },
  sensacaoHero: {
    fontFamily: Typography.body,
    color: Colors.textMuted,
    fontSize: 12,
    textAlign: 'right',
  },
  linhaMinMax: {
    flexDirection: 'row',
    gap: Spacing.lg,
    marginTop: Spacing.md,
  },
  blocoMinMax: { alignItems: 'flex-start' },
  rotuloMinMax: {
    fontFamily: Typography.display,
    color: Colors.textMuted,
    fontSize: 7,
    letterSpacing: 3,
    marginBottom: 2,
  },
  valorMinMax: {
    fontFamily: Typography.display,
    fontSize: 20,
  },
  atualizadoEm: {
    fontFamily: Typography.body,
    color: Colors.textMuted,
    fontSize: 10,
    marginTop: Spacing.sm,
    letterSpacing: 0.5,
  },

  grade: {
    gap: Spacing.sm,
    marginBottom: Spacing.md,
    paddingHorizontal: Spacing.md,
  },
  linhaGrade: { flexDirection: 'row', gap: Spacing.sm },
  celulaGrade: { flex: 1 },

  containerPrevisao: {
    paddingHorizontal: Spacing.md,
    marginBottom: Spacing.md,
  },
  cardPrevisao: {
    backgroundColor: Colors.bgCard,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden',
  },
  itemPrevisao: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    gap: Spacing.sm,
  },
  itemPrevisaoUltimo: {
    borderBottomWidth: 0,
  },
  dataPrevisao: {
    fontFamily: Typography.bodyMedium,
    color: Colors.textPrimary,
    fontSize: 13,
    width: 90,
    textTransform: 'capitalize',
  },
  emojiPrevisao: { fontSize: 20, width: 30, textAlign: 'center' },
  chuvaPrevisao: {
    fontFamily: Typography.body,
    color: '#4fc3f7',
    fontSize: 11,
    width: 36,
    textAlign: 'center',
  },
  tempsPrevisao: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginLeft: 'auto' as any,
    alignItems: 'center',
  },
  tempMinPrevisao: {
    fontFamily: Typography.body,
    color: Colors.textSecondary,
    fontSize: 13,
    width: 32,
    textAlign: 'right',
  },
  tempMaxPrevisao: {
    fontFamily: Typography.display,
    color: Colors.textPrimary,
    fontSize: 13,
    width: 32,
    textAlign: 'right',
  },

  rodape: {
    fontFamily: Typography.body,
    color: Colors.textMuted,
    fontSize: 10,
    textAlign: 'center',
    letterSpacing: 0.5,
    marginTop: Spacing.sm,
    paddingHorizontal: Spacing.md,
    marginBottom: Spacing.md,
  },

  estadoInicial: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.xxl,
    gap: Spacing.md,
  },
  emojiInicial: { fontSize: 64 },
  tituloInicial: {
    fontFamily: Typography.display,
    color: Colors.textPrimary,
    fontSize: 16,
    letterSpacing: 2,
    textAlign: 'center',
  },
  subInicial: {
    fontFamily: Typography.body,
    color: Colors.textSecondary,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 20,
  },
});
